VoguishTemplate/Controllers/AuthorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VoguishTemplate.Models;

namespace VoguishTemplate.Controllers
{
    public class AuthorController : Controller
    {
        private VoguishEntities db = new VoguishEntities();
        // GET: Author
        public ActionResult Index()
        {
            return View(db.Authors.ToList());
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Author author)
        {
            db.Authors.Add(author);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Delete(int Id)
        {
            Author aut = db.Authors.Find(Id);
            return View(aut);
        }

        [HttpPost]
        public ActionResult Delete(Author author)
        {
            Author aut = db.Authors.Find(author.Id);
            db.Authors.Remove(aut);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(int Id)
        {
            Author aut = db.Authors.Find(Id);
            return View(aut);
        }

        [HttpPost]
        public ActionResult Edit(Author author)
        {
            Author aut = db.Authors.Find(author.Id);
            aut.Name = author.Name;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

VoguishTemplate/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VoguishTemplate.Models;

namespace VoguishTemplate.Controllers
{
    public class CategoryController : Controller
    {
        private VoguishEntities db = new VoguishEntities();
        // GET: Category
        public ActionResult Index()
        {
            return View(db.Categories.ToList());
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Category cat)
        {
            db.Categories.Add(cat);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Delete(int Id)
        {
            Category cat = db.Categories.Find(Id);
            return View(cat);
        }

        [HttpPost]
        public ActionResult Delete(Category category)
        {
            Category cat = db.Categories.Find(category.Id);
            db.Categories.Remove(cat);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(int Id)
        {
            Category cat = db.Categories.Find(Id);
            return View(cat);
        }

        [HttpPost]
        public ActionResult Edit(Category category)
        {
            Category cat = db.Categories.Find(category.Id);
            cat.Name = category.Name;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

VoguishTemplate/Controllers/FilessController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VoguishTemplate.Models;
using System.IO;

namespace VoguishTemplate.Controllers
{
    public class FilessController : Controller
    {
        private VoguishEntities db = new VoguishEntities();
        public string FileName;
        public string FilePath;
        public int FileSize;
        public string FileExtention;
        // GET: File
        public ActionResult Index()
        {
            return View(db.Filesses.ToList());
        }

        [HttpGet]
        public ActionResult Upload()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Upload(HttpPostedFileBase Image)
        {
            if (Image.ContentLength > 0) 
            {
                FileName = Path.GetFileName(Image.FileName);
                FilePath = Path.Combine(Server.MapPath("~/Uploads/"), FileName);
                FileExtention = Path.GetExtension(FileName);
                FileSize = Image.ContentLength;
                Image.SaveAs(FilePath);
            }
            Filess File = new Filess();
            File.Name = FileName;
            File.Extention = FileExtention;
            File.Path = FilePath;
            File.Size = FileSize;
            db.Filesses.Add(File);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Delete(int Id)
        {
            Filess file = db.Filesses.Find(Id);
            return View(file);
        }

        [HttpPost]
        public ActionResult Delete(Filess file)
        {
            Filess files = db.Filesses.Find(file.Id);
            db.Filesses.Remove(files);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

VoguishTemplate/Controllers/LinkController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VoguishTemplate.Models;

namespace VoguishTemplate.Controllers
{
    public class LinkController : Controller
    {
        private VoguishEntities db = new VoguishEntities();
        // GET: Link
        public ActionResult Index()
        {
            return View(db.Links.ToList());
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Link links)
        {
            db.Links.Add(links);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Delete(int Id)
        {
            Link links = db.Links.Find(Id);
            return View(links);
        }

        [HttpPost]
        public ActionResult Delete(Link links)
        {
            Link li = db.Links.Find(links.Id);
            db.Links.Remove(li);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(int Id)
        {
            Link links = db.Links.Find(Id);
            return View(links);
        }

        [HttpPost]
        public ActionResult Edit(Link links)
        {
            Link li = db.Links.Find(links.Id);
            li.Name = links.Name;
            li.Url = links.Url;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

VoguishTemplate/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Voguish Home", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Authors", "Index", "Author")</li>
                    <li>@Html.ActionLink("Categories", "Index", "Category")</li>
                    <li>@Html.ActionLink("Files", "Index", "Filess")</li>
                    <li>@Html.ActionLink("Links", "Index", "Link")</li>
                    <li>@Html.ActionLink("Menus", "Index", "Menus")</li>
                    <li>@Html.ActionLink("News", "Index", "News")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

VoguishTemplate/Views/Shared/_LayoutPage1.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Voguish a Blogging Category Flat Bootstarp Responsive Website Template | Home :: w3layouts</title>
    <link href="~/Content/style.css" rel="stylesheet" type="text/css" media="all" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" type="text/css" media="all" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Voguish Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
    
    
    
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:200,300,400,600,700,900' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Libre+Baskerville:400,700' rel='stylesheet' type='text/css'>
    @Scripts.Render("~/Scripts/js")
    <script>
    $(function () {
      $("#slider").responsiveSlides({
      	auto: true,
      	nav: true,
      	speed: 500,
        namespace: "callbacks",
        pager: true,
      });
    });

    </script>
</head>
<body>
    
        <!-- header -->
        <div class="header">
            <div class="container">
                <div class="logo">
                    <a href="index.html"><img src="~/Content/images/logo.png" class="img-responsive" alt=""></a>
                </div>

                <div class="head-nav">
                    <span class="menu"> </span>
                    <ul class="cl-effect-1">
                        <li class="active"><a href="index.html">Home</a></li>
                        <li><a href="about.html">About Us</a></li>
                        <li><a href="services.html">Services</a></li>
                        <li><a href="blog.html">Blog</a></li>
                        <li><a href="404.html">Shortcodes</a></li>
                        <li><a href="login.html">Login</a></li>
                        <li><a href="contact.html">Contact</a></li>
                        <div class="clearfix"></div>
                    </ul>
                </div>
                <!-- script-for-nav -->
                <script>
                    $("span.menu").click(function () {
                        $(".head-nav ul").slideToggle(300, function () {
                            // Animation complete.
                        });
                    });
                </script>
                <!-- script-for-nav -->
                <div class="clearfix"> </div>
            </div>
        </div>
        <!-- header -->
    <div class="container">
        <div>
            @RenderBody()
        </div>

        <div class="footer">
            <div class="col-md-3 foot-1">
                <h4>Quick Links</h4>
                <ul>
                    <li><a href="#">||   Lorem Ipsum passage</a></li>
                    <li><a href="#">||   Finibus Bonorum et</a></li>
                    <li><a href="#">||   Treatise on the theory</a></li>
                </ul>
            </div>
            <div class="col-md-3 foot-1">
                <h4>Favorite Resources</h4>
                <ul>
                    <li><a href="#">||   Characteristic words</a></li>
                    <li><a href="#">||   combined with a handful</a></li>
                    <li><a href="#">||   which looks reasonable</a></li>
                </ul>
            </div>
            <div class="col-md-3 foot-1">
                <h4>About Us</h4>
                <ul>
                    <li><a href="#">||  Even slightly believable</a></li>
                    <li><a href="#">||  Hidden in the middle</a></li>
                    <li><a href="#">||  Ipsum therefore always</a></li>
                </ul>
            </div>
            <div class="col-md-3 foot-1">
                <h4>Custom Menu</h4>
                <ul>
                    <li><a href="#">||  Internet tend to repeat</a></li>
                    <li><a href="#">||  Alteration in some form</a></li>
                    <li><a href="#">||  This book is a treatise</a></li>
                </ul>
            </div>

            <div class="clearfix"> </div>
            <div class="copyright">
                <p>Copyrights © 2015 Voguish All rights reserved | Template by <a href="http://w3layouts.com/">W3layouts</a></p>
            </div>
        </div>
    </div>
</body>
</html>