VoguishTemplate/Models/Menu.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoguishTemplate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Url { get; set; }
        public int Link_Id { get; set; }
    
        public virtual Link Link { get; set; }
    }
}

VoguishTemplate/Controllers/MenuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VoguishTemplate.Models;

namespace VoguishTemplate.Controllers
{
    public class MenuController : Controller
    {
        private VoguishEntities db = new VoguishEntities();
        // GET: Menu
        public ActionResult Index()
        {
            return View(db.Menus.ToList());
        }

        public ActionResult Create()
        {
            return View();
        }

        public ActionResult Create(Menu menuu)
        {
            return View();
        }
    }
}

VoguishTemplate/Controllers/MenusController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VoguishTemplate.Models;

namespace VoguishTemplate.Controllers
{
    public class MenusController : Controller
    {
        private VoguishEntities db = new VoguishEntities();
        public int Id;
        // GET: Menus
        public ActionResult Index()
        {
            return View(db.Menus.ToList());
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View(db.Links.ToList());
        }

        [HttpPost]
        public ActionResult Create(string Name, string Url, string Link)
        {
            Menu menus = new Menu();
            var LinkList = db.Links.ToList();
            var Men = (from menu in LinkList
                       where menu.Name == Link
                       select new { Id = menu.Id }).Single();
            menus.Name = Name;
            menus.Url = Url;
            menus.Link_Id = Men.Id;
            db.Menus.Add(menus);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Delete(int Id)
        {
            Menu menu = db.Menus.Find(Id);
            return View(menu);
        }

        [HttpPost]
        public ActionResult Delete(Menu m)
        {
            Menu menus = db.Menus.Find(m.Id);
            db.Menus.Remove(menus);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(int Id)
        {
            ViewBag.links = db.Links.ToList();
            Menu menu = db.Menus.Find(Id);
            return View(menu);
        }

        [HttpPost]
        public ActionResult Edit([Bind(Exclude = "Link_Id")] Menu m, string Link_Id)
        {
            Menu menus = db.Menus.Find(m.Id);
            menus.Name = m.Name;
            menus.Url = m.Url;
            menus.Link_Id = Convert.ToInt32(Link_Id);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

VoguishTemplate/Views/Menus/Create.cshtml
@model IEnumerable<VoguishTemplate.Models.Link>
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Add Menu</h2>
@using (Html.BeginForm("Create", "Menus", FormMethod.Post, new { enctype = "multipart/form-data", @class = "form-horizontal" }))
{
    <div class="form-group">
        <label class="control-label col-sm-2" for="name">Name:</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" id="name" placeholder="Name" name="Name">
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-sm-2" for="url">Url:</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" id="name" placeholder="Url" name="Url">
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-sm-2" for="link">Link:</label>
        <div class="col-sm-10">
            <select id="link" class="form-control" name="Link">
                @foreach (var item in Model)
                {
                    <option>@item.Name</option>
                }
            </select>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-default">Add</button>
        </div>
    </div>
}

VoguishTemplate/Views/Menus/Delete.cshtml
@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete News</h2>

@using (Html.BeginForm("Delete", "Menus", FormMethod.Post))
{
    <div class="form-group">
        <label for="name">Name:</label>
        <input type="text" class="form-control" id="name" name="@Model.Id" placeholder="@Model.Name">
    </div>
    <div class="form-group">
        <label for="name">Url:</label>
        <input type="text" class="form-control" id="name" placeholder="@Model.Url">
    </div>
    <div class="form-group">
        <button class="btn btn-default" type="submit">Delete</button>
    </div>
}

VoguishTemplate/Views/Menus/Edit.cshtml
@model VoguishTemplate.Models.Menu
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>
@using (Html.BeginForm("Edit", "Menus", FormMethod.Post))
{
    <div class="form-group">
        <label for="name">Name:</label>
        <input type="text" class="form-control" id="name" name="Name" placeholder="@Model.Name">
    </div>
    <div class="form-group">
        <label for="url">Url:</label>
        <input type="text" class="form-control" id="url" name="Url" placeholder="@Model.Url">
    </div>
    <div class="form-group">
        <label for="link">Link:</label>
        <input type="text" class="form-control" id="link" placeholder="@Model.Link_Id">
    </div>
    <div class="form-group">
        <label for="links">Link Id:</label>
            <select id="links" class="form-control"  name="Link_Id">
                @foreach (var item in ViewBag.links)
                {
                    <option>@item.Id</option>
                }
            </select>
    </div>
    <div class="form-group">
        <button class="btn btn-default" type="submit">Edit</button>
    </div>
}

VoguishTemplate/Views/Menus/Index.cshtml
@model IEnumerable<VoguishTemplate.Models.Menu>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Menus</h2>
<button class="btn btn-default">@Html.ActionLink("Add Menu", "Create")</button>
<br />
<table class="table table-bordered">
    <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Url</th>
            <th>Link</th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.Name</td>
                <td>@item.Url</td>
                <td>@item.Link.Name</td>
                <td>@Html.ActionLink("Delete", "Delete", new { Id = item.Id })</td>
                <td>@Html.ActionLink("Edit", "Edit", new { Id = item.Id })</td>
            </tr>
        }
    </tbody>
</table>